<?xml version="1.0" encoding="UTF-8" ?>
<definitions
    targetNamespace="http://tempuri.org/wsdl/"
    xmlns:wsdlns="http://tempuri.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:stk="http://schemas.microsoft.com/soap-toolkit/wsdl-extension"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
>
    <message name="foo"/>

    <message name="fooResponse">
        <part name="result" type="xsd:string"/>
    </message>

    <portType name="FooPort">
        <operation name="foo">
            <input message="wsdlns:foo"/>
            <output message="wsdlns:fooResponse"/>
        </operation>
    </portType>

    <binding name="FooBinding" type="FooPort">
        <stk:binding preferredEncoding="UTF-8" />
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="foo">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>

    <service name="FooService">
        <port name="FooPort" binding="wsdlns:FooBinding">
            <soap:address location="http://127.0.0.1:8080/soap.php"/>
        </port>
    </service>
</definitions>